export const cardDeck = [
  { name: 'Ahearts', image: 'hearts_A.webp' },
  { name: '2hearts', image: 'hearts_2.webp' },
  { name: '3hearts', image: 'hearts_3.webp' },
  { name: '4hearts', image: 'hearts_4.webp' },
  { name: '5hearts', image: 'hearts_5.webp' },
  { name: '6hearts', image: 'hearts_6.webp' },
  { name: '7hearts', image: 'hearts_7.webp' },
  { name: '8hearts', image: 'hearts_8.webp' },
  { name: '9hearts', image: 'hearts_9.webp' },
  { name: '10hearts', image: 'hearts_10.webp' },
  { name: 'Jhearts', image: 'hearts_J.webp' },
  { name: 'Qhearts', image: 'hearts_Q.webp' },
  { name: 'Khearts', image: 'hearts_K.webp' },

  { name: 'Aclubs', image: 'clubs_A.webp' },
  { name: '2clubs', image: 'clubs_2.webp' },
  { name: '3clubs', image: 'clubs_3.webp' },
  { name: '4clubs', image: 'clubs_4.webp' },
  { name: '5clubs', image: 'clubs_5.webp' },
  { name: '6clubs', image: 'clubs_6.webp' },
  { name: '7clubs', image: 'clubs_7.webp' },
  { name: '8clubs', image: 'clubs_8.webp' },
  { name: '9clubs', image: 'clubs_9.webp' },
  { name: '10clubs', image: 'clubs_10.webp' },
  { name: 'Jclubs', image: 'clubs_J.webp' },
  { name: 'Qclubs', image: 'clubs_Q.webp' },
  { name: 'Kclubs', image: 'clubs_K.webp' },

  { name: 'Aspades', image: 'spades_A.webp' },
  { name: '2spades', image: 'spades_2.webp' },
  { name: '3spades', image: 'spades_3.webp' },
  { name: '4spades', image: 'spades_4.webp' },
  { name: '5spades', image: 'spades_5.webp' },
  { name: '6spades', image: 'spades_6.webp' },
  { name: '7spades', image: 'spades_7.webp' },
  { name: '8spades', image: 'spades_8.webp' },
  { name: '9spades', image: 'spades_9.webp' },
  { name: '10spades', image: 'spades_10.webp' },
  { name: 'Jspades', image: 'spades_J.webp' },
  { name: 'Qspades', image: 'spades_Q.webp' },
  { name: 'Kspades', image: 'spades_K.webp' },

  { name: 'Adiamonds', image: 'diamonds_A.webp' },
  { name: '2diamonds', image: 'diamonds_2.webp' },
  { name: '3diamonds', image: 'diamonds_3.webp' },
  { name: '4diamonds', image: 'diamonds_4.webp' },
  { name: '5diamonds', image: 'diamonds_5.webp' },
  { name: '6diamonds', image: 'diamonds_6.webp' },
  { name: '7diamonds', image: 'diamonds_7.webp' },
  { name: '8diamonds', image: 'diamonds_8.webp' },
  { name: '9diamonds', image: 'diamonds_9.webp' },
  { name: '10diamonds', image: 'diamonds_10.webp' },
  { name: 'Jdiamonds', image: 'diamonds_J.webp' },
  { name: 'Qdiamonds', image: 'diamonds_Q.webp' },
  { name: 'Kdiamonds', image: 'diamonds_K.webp' },
]
