export const cardDeck = [
  { name: 'Ahearts', image: 'hearts_A.png' },
  { name: '2hearts', image: 'hearts_2.png' },
  { name: '3hearts', image: 'hearts_3.png' },
  { name: '4hearts', image: 'hearts_4.png' },
  { name: '5hearts', image: 'hearts_5.png' },
  { name: '6hearts', image: 'hearts_6.png' },
  { name: '7hearts', image: 'hearts_7.png' },
  { name: '8hearts', image: 'hearts_8.png' },
  { name: '9hearts', image: 'hearts_9.png' },
  { name: '10hearts', image: 'hearts_10.png' },
  { name: 'Jhearts', image: 'hearts_J.png' },
  { name: 'Qhearts', image: 'hearts_Q.png' },
  { name: 'Khearts', image: 'hearts_K.png' },

  { name: 'Aclubs', image: 'clubs_A.png' },
  { name: '2clubs', image: 'clubs_2.png' },
  { name: '3clubs', image: 'clubs_3.png' },
  { name: '4clubs', image: 'clubs_4.png' },
  { name: '5clubs', image: 'clubs_5.png' },
  { name: '6clubs', image: 'clubs_6.png' },
  { name: '7clubs', image: 'clubs_7.png' },
  { name: '8clubs', image: 'clubs_8.png' },
  { name: '9clubs', image: 'clubs_9.png' },
  { name: '10clubs', image: 'clubs_10.png' },
  { name: 'Jclubs', image: 'clubs_J.png' },
  { name: 'Qclubs', image: 'clubs_Q.png' },
  { name: 'Kclubs', image: 'clubs_K.png' },

  { name: 'Aspades', image: 'spades_A.png' },
  { name: '2spades', image: 'spades_2.png' },
  { name: '3spades', image: 'spades_3.png' },
  { name: '4spades', image: 'spades_4.png' },
  { name: '5spades', image: 'spades_5.png' },
  { name: '6spades', image: 'spades_6.png' },
  { name: '7spades', image: 'spades_7.png' },
  { name: '8spades', image: 'spades_8.png' },
  { name: '9spades', image: 'spades_9.png' },
  { name: '10spades', image: 'spades_10.png' },
  { name: 'Jspades', image: 'spades_J.png' },
  { name: 'Qspades', image: 'spades_Q.png' },
  { name: 'Kspades', image: 'spades_K.png' },

  { name: 'Adiamonds', image: 'diamonds_A.png' },
  { name: '2diamonds', image: 'diamonds_2.png' },
  { name: '3diamonds', image: 'diamonds_3.png' },
  { name: '4diamonds', image: 'diamonds_4.png' },
  { name: '5diamonds', image: 'diamonds_5.png' },
  { name: '6diamonds', image: 'diamonds_6.png' },
  { name: '7diamonds', image: 'diamonds_7.png' },
  { name: '8diamonds', image: 'diamonds_8.png' },
  { name: '9diamonds', image: 'diamonds_9.png' },
  { name: '10diamonds', image: 'diamonds_10.png' },
  { name: 'Jdiamonds', image: 'diamonds_J.png' },
  { name: 'Qdiamonds', image: 'diamonds_Q.png' },
  { name: 'Kdiamonds', image: 'diamonds_K.png' },
]
