name: ArgoCD Sync

on:
  workflow_run:
    workflows: ["Release and Build Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read

    steps:
      - name: Notify ArgoCD
        env:
          ARGOCD_WEBHOOK_SECRET: ${{ secrets.ARGOCD_WEBHOOK_SECRET }}
          ARGOCD_WEBHOOK_URL: https://argo.dev4ever.app/api/webhook
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          REPO_URL="https://github.com/$GITHUB_REPOSITORY.git"

          PAYLOAD=$(jq -n \
            --arg ref "$GITHUB_REF" \
            --arg after "$GITHUB_SHA" \
            --arg before "" \
            --arg full_name "$GITHUB_REPOSITORY" \
            --arg clone_url "$REPO_URL" \
            --arg pusher_name "$GITHUB_ACTOR" \
            '{
              ref: $ref,
              after: $after,
              before: $before,
              repository: {
                full_name: $full_name,
                clone_url: $clone_url
              },
              pusher: {
                name: $pusher_name
              },
              head_commit: null,
              commits: [],
              created: false,
              deleted: false,
              forced: false
            }')

          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$ARGOCD_WEBHOOK_SECRET" | sed 's/^.* //')

          curl -X POST "$ARGOCD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -d "$PAYLOAD"