name: ArgoCD Sync

on:
  workflow_run:
    workflows: ["Release and Build Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read

    steps:
      - name: Notify ArgoCD
        env:
          ARGOCD_WEBHOOK_SECRET: ${{ secrets.ARGOCD_WEBHOOK_SECRET }}
          ARGOCD_WEBHOOK_URL: https://argo.dev4ever.app/api/webhook
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          REPO_URL="https://github.com/$GITHUB_REPO.git"
          PAYLOAD=$(printf '{"ref":"%s","repository":{"full_name":"%s","clone_url":"%s"}}' "$GITHUB_REF" "$GITHUB_REPO" "$REPO_URL")

          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$ARGOCD_WEBHOOK_SECRET" | sed 's/^.* //')

          curl -X POST "$ARGOCD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
            -d "$PAYLOAD"