name: Deploy to Koyeb

on:
  workflow_run:
    workflows: ["Release and Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: aclhu4www5xc3nxlyrutl6feospyrqj26xjwv2nh5q1trsf57e28dpyiz77xou09
      - name: Deploy to Koyeb
        run: |
          koyeb service redeploy electronic-elset/yaya-developer